### PR TITLE
PDQ-10008 fix django2 imports

### PR DESCRIPTION
**Pull request by ghost**
**Note**: oauth2client is now deprecated. As such, it is unlikely that we will
review or merge to your pull request. We recommend you use
[google-auth](https://google-auth.readthedocs.io) and [oauthlib](http://oauthlib.readthedocs.io/).

# [PDQ-10008](https://consumeraffairs.atlassian.net/browse/PDQ-10008)

☝️ since oauth2client is not maintained, we forked it and are performing only the required changes to make it work with django 2.2. So far, the import structure is the only known defect, but we can't be 💯% certain until we try. 🤞 

[PDQ-10008]: https://consumeraffairs.atlassian.net/browse/PDQ-10008

### CODE REVIEW

**Review by kviktor — CHANGES_REQUESTED** [review]
Can you please also bump version so we can do a release and then change the requirements in mainsite to use the new code.

**Comment by ghost** [comment]
Do we make releases for forked libraries like this? I thought we just imported the CA/project branch at latest wherever we needed it. In this case, I think we're going to remove it entirely as soon as we get a chance to update to a newer library that is still being maintained.

**Comment by kviktor** [comment]
We can install via git commit hash too yo are right. Can you merge this PR then and create the bump in mainsite? (I don't have write access to this repo)

**Review by kviktor — APPROVED** [review]

**Comment by ghost** [comment]
I don't have write access either.... @wsantos can you merge please?

**Pull request merged**
